openapi: 3.0.3
info:
  title: Swagger Customer specific test
  description: |-
    API to get all CSTs available
    - Method: GET
    - Request payload: nill
    - Response body: Available list of CSTs for the given details. (empty array if no tests available)

    API to trigger the CI builds.
    - Method: POST
    - Request payload: (parameters we discussed the other day) Customer key, product name, product version etc.
    - Response body: Assigned queue/test ID

    API to update CI status in tables
    - Method: POST
    - Request payload: nill
    - Response payload: nill

    API to trigger the CD builds acoording the updated details in the tables
    - Method: POST
    - Request payload: nill
    - Response payload: nill

    API to check the status of the processed/processing CSTs with the given test ID.
    - Method: POST
    - Path parameter: Test ID
    - Request Payload: nill
    - Response body: Details of the CSTs related to the given test ID. (array of CST name, test status [QUEUED, PROCESSING, PASSED, FAILED, TERMINATED], message (eg: failure message))

    API to re-trigger the failed CI builds
    - Method: POST
    - Path parameter: Test ID
    - Request payload: nill
    - Response payload: nill

    API to cleanup ACR once a week
    - Method: POST
    - Request payload: nill
    - Response payload: nill

    
  version: 1.0.11
servers:
  - url: http://localhost:5000/cst\

components:
  securitySchemes:
    oauth2sample:
      type: oauth2
      flows: 
        authorizationCode:
          authorizationUrl: https://api.asgardeo.io/t/wso2/oauth2/authorize
          tokenUrl: https://api.asgardeo.io/t/wso2/oauth2/token
          scopes:
            accessTable: access tables
            umtEndpoints: use endpoints

tags:
  - name: cst
    description: Customer specific tests
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  "/customer":
    get:
      tags:
        - cst
      summary: Returns all the ARR custmer details with their products
      description: Returns all the ARR custmer details with their products
      operationId: addPet
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                example:
                  - id: 3bbc5c46-fd11-4408-b5ba-46aef64223ba
                    customer_key: BNYM
                    product_name: wso2am
                    product_base_version: 3.2.0
                  - id: 5b0aa9cc-b146-4cb6-ac2d-a75dc33aee8a
                    customer_key: Credit Agricole
                    product_name: wso2am
                    product_base_version: 3.2.0
                  - id: c6c5c7d5-63dc-4e2c-a2bc-7571c198e6c9
                    customer_key: BNYM
                    product_name: wso2ei
                    product_base_version: "1.8"
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - oauth2sample: [umtEndpoints]
      
  "/builds":
    post:
      tags:
        - cst
      summary: Trigger CI builds
      description:
        Returns the UUID specified to a specific chunk
      requestBody:
        description: 
          Provide the list of object with the respective product and product version which the u2 updates are applicable
          OR
          Provide a JSON object for hostfix update
        content:
          application/json:
            schema:
              oneOf:
              - type: array
                items:
                  type: object
                  properties: 
                    product_name:
                      type: string
                    product_base_version:
                      type: string
                  example:
                    - productName: "wso2am"
                      productBaseVersion: "3.2.0"
                    - productName: "wso2ei"
                      productBaseVersion: "1.8"
              - type: object
                example: 
                - productName: "wso2am"
                  productVersion: "4.2.0"
                  customerKey: "BNYM"
                  hotfixFilePath: "XXX.zip"
        required: true
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: string
                example:
                  i942c46f6-20bb-4f4c-a5e6-9a6b8e28ff9f
      security:
        - oauth2sample: [umtEndpoints]
  "/builds/ci/status":
    post:
      tags:
        - cst
      summary: Update CI builds status
      description: Update the CI build table values according to the CI builds status
      responses:
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - oauth2sample: [accessTable]
  "/builds/cd/trigger":
    post:
      tags:
        - cst
      summary: Trigger the related CD builds
      description: Add entries to CD build table
      responses:
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - oauth2sample: [accessTable]
  "/builds/cd/status":
    post:
      tags:
        - cst
      summary: Update CI builds status
      description: Update the CD build table values according to the CD builds status
      responses:
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - oauth2sample: [accessTable]
  "/builds/{cicdId}":
    get:
      tags:
        - cst
      summary: Get the CI and CD builds job status
      description: Get the CI and CD builds job status
      parameters:
        - name: cicdId
          in: path
          description: cicdId to delete
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid cicdId value
      security:
        - oauth2sample: [umtEndpoints]
  "/builds/{cicdId}/re-trigger":
      post:
        tags:
          - cst
        summary: Trigger the failed CI builds
        description: Trigger the failed CI builds
        parameters:
          - name: cicdId
            in: path
            description: Pet id to delete
            required: true
            schema:
              type: string
        responses:
          '400':
            description: Invalid cicdId value
        security:
        - oauth2sample: [umtEndpoints]
  "/acr-cleanup":
      post:
        tags:
          - cst
        summary: Delete acr repositories once a week
        description: Delete the unwanted images in the ACR once a week
        responses:
          '400':
            description: Invalid input
          '422':
            description: Validation exception
        security:
        - oauth2sample: [umtEndpoints]